# -*- coding: utf-8 -*-
"""Deck of cards.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g8GZoHT9V-OdJ7YQB5mZRn1PDsyBqrY1
"""

import random

class Card(object):
  def __init__(self, val, suit):
    self.value = val
    self.suit = suit
  def show(self):
    print( "{} of {}".format(self.value, self.suit))

#card = Card(6, "Club")
#card.show()

class Deck(object):
  def __init__(self):
    self.cards = []
    self.build()
  
  def build(self):
    for s in ["Spades", "Clubs", "Diamonds", "Hearts"]:
      for v in range(1,14):
        self.cards.append(Card(v,s));

  def show(self):
    for card in self.cards:
      card.show();

  def shuffle(self):
    for i in range(len(self.cards)-1, 0, -1):
      r  = random.randint(0,i);
      self.cards[i], self.cards[r] = self.cards[r], self.cards[i];
  def draw(self):
    return self.cards.pop();
deck = Deck();
deck.shuffle()
#deck.show()
card = deck.draw()
card.show()

class Player(object):
  def __init__(self):
    self.hand = [];
  def draw(self,deck):
    self.hand.append(deck.draw());
    return self;
  def showHand(self):
    for card in self.hand:
      card.show();
  def discard(self):
    self.hand.pop().show();

player1 = Player();
player1.draw(deck).draw(deck);
player1.showHand()
player1.discard()